[2023-05-31T02:03:47.468+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:03:45.527323+00:00 [queued]>
[2023-05-31T02:03:47.481+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:03:45.527323+00:00 [queued]>
[2023-05-31T02:03:47.481+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T02:03:47.482+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-05-31T02:03:47.482+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T02:03:47.507+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): created_folders_task> on 2023-05-31 02:03:45.527323+00:00
[2023-05-31T02:03:47.515+0000] {standard_task_runner.py:55} INFO - Started process 1615 to run task
[2023-05-31T02:03:47.519+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'captura_dados', 'created_folders_task', 'manual__2023-05-31T02:03:45.527323+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/captura_dados.py', '--cfg-path', '/tmp/tmppumpvlmw']
[2023-05-31T02:03:47.521+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask created_folders_task
[2023-05-31T02:03:47.595+0000] {task_command.py:388} INFO - Running <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:03:45.527323+00:00 [running]> on host 5219a5ad576c
[2023-05-31T02:03:47.691+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=captura_dados
AIRFLOW_CTX_TASK_ID=created_folders_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-31T02:03:45.527323+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-31T02:03:45.527323+00:00
[2023-05-31T02:03:47.697+0000] {logging_mixin.py:137} INFO - Pasta data j√° existe!
[2023-05-31T02:03:47.697+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/captura_dados.py", line 33, in created_folders
    os.makedirs(created_files_path + i)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/airflowengineer'
[2023-05-31T02:03:47.706+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=captura_dados, task_id=created_folders_task, execution_date=20230531T020345, start_date=20230531T020347, end_date=20230531T020347
[2023-05-31T02:03:47.719+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task created_folders_task ([Errno 13] Permission denied: '/opt/airflowengineer'; 1615)
[2023-05-31T02:03:47.770+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-31T02:03:47.795+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
