[2023-05-27T19:36:03.419+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:35:43.990548+00:00 [queued]>
[2023-05-27T19:36:03.436+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:35:43.990548+00:00 [queued]>
[2023-05-27T19:36:03.437+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:36:03.438+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-05-27T19:36:03.438+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:36:03.462+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): permissoes_diretorios> on 2023-05-27 19:35:43.990548+00:00
[2023-05-27T19:36:03.469+0000] {standard_task_runner.py:55} INFO - Started process 1349 to run task
[2023-05-27T19:36:03.473+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cria_diretorios_projeto', 'permissoes_diretorios', 'manual__2023-05-27T19:35:43.990548+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/cria_diretorios_projeto.py', '--cfg-path', '/tmp/tmppu2n9s8o']
[2023-05-27T19:36:03.475+0000] {standard_task_runner.py:83} INFO - Job 225: Subtask permissoes_diretorios
[2023-05-27T19:36:03.580+0000] {task_command.py:388} INFO - Running <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:35:43.990548+00:00 [running]> on host 36658c0564dd
[2023-05-27T19:36:03.709+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cria_diretorios_projeto
AIRFLOW_CTX_TASK_ID=permissoes_diretorios
AIRFLOW_CTX_EXECUTION_DATE=2023-05-27T19:35:43.990548+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-27T19:35:43.990548+00:00
[2023-05-27T19:36:03.712+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-27T19:36:03.716+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', None]
[2023-05-27T19:36:03.719+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 83, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-05-27T19:36:03.735+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=cria_diretorios_projeto, task_id=permissoes_diretorios, execution_date=20230527T193543, start_date=20230527T193603, end_date=20230527T193603
[2023-05-27T19:36:03.757+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 225 for task permissoes_diretorios (expected str, bytes or os.PathLike object, not NoneType; 1349)
[2023-05-27T19:36:03.780+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-27T19:36:03.810+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
