[2023-05-27T19:39:26.035+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:35:43.990548+00:00 [queued]>
[2023-05-27T19:39:26.053+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:35:43.990548+00:00 [queued]>
[2023-05-27T19:39:26.054+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:39:26.054+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2023-05-27T19:39:26.054+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:39:26.112+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): permissoes_diretorios> on 2023-05-27 19:35:43.990548+00:00
[2023-05-27T19:39:26.126+0000] {standard_task_runner.py:55} INFO - Started process 1558 to run task
[2023-05-27T19:39:26.137+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cria_diretorios_projeto', 'permissoes_diretorios', 'manual__2023-05-27T19:35:43.990548+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/cria_diretorios_projeto.py', '--cfg-path', '/tmp/tmp049thnzm']
[2023-05-27T19:39:26.142+0000] {standard_task_runner.py:83} INFO - Job 228: Subtask permissoes_diretorios
[2023-05-27T19:39:26.286+0000] {task_command.py:388} INFO - Running <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:35:43.990548+00:00 [running]> on host 36658c0564dd
[2023-05-27T19:39:26.417+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cria_diretorios_projeto
AIRFLOW_CTX_TASK_ID=permissoes_diretorios
AIRFLOW_CTX_EXECUTION_DATE=2023-05-27T19:35:43.990548+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-27T19:35:43.990548+00:00
[2023-05-27T19:39:26.421+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-27T19:39:26.422+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', None]
[2023-05-27T19:39:26.423+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 83, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-05-27T19:39:26.436+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=cria_diretorios_projeto, task_id=permissoes_diretorios, execution_date=20230527T193543, start_date=20230527T193926, end_date=20230527T193926
[2023-05-27T19:39:26.467+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 228 for task permissoes_diretorios (expected str, bytes or os.PathLike object, not NoneType; 1558)
[2023-05-27T19:39:26.518+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-27T19:39:26.560+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
