[2023-05-27T19:44:31.756+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:44:17.558652+00:00 [queued]>
[2023-05-27T19:44:31.767+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:44:17.558652+00:00 [queued]>
[2023-05-27T19:44:31.768+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:44:31.768+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-05-27T19:44:31.768+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:44:31.787+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): permissoes_diretorios> on 2023-05-27 19:44:17.558652+00:00
[2023-05-27T19:44:31.794+0000] {standard_task_runner.py:55} INFO - Started process 1898 to run task
[2023-05-27T19:44:31.798+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cria_diretorios_projeto', 'permissoes_diretorios', 'manual__2023-05-27T19:44:17.558652+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/cria_diretorios_projeto.py', '--cfg-path', '/tmp/tmpgh84ad2a']
[2023-05-27T19:44:31.800+0000] {standard_task_runner.py:83} INFO - Job 242: Subtask permissoes_diretorios
[2023-05-27T19:44:31.871+0000] {task_command.py:388} INFO - Running <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:44:17.558652+00:00 [running]> on host 36658c0564dd
[2023-05-27T19:44:31.952+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cria_diretorios_projeto
AIRFLOW_CTX_TASK_ID=permissoes_diretorios
AIRFLOW_CTX_EXECUTION_DATE=2023-05-27T19:44:17.558652+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-27T19:44:17.558652+00:00
[2023-05-27T19:44:31.954+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-27T19:44:31.955+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', None]
[2023-05-27T19:44:31.956+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 83, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-05-27T19:44:31.966+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=cria_diretorios_projeto, task_id=permissoes_diretorios, execution_date=20230527T194417, start_date=20230527T194431, end_date=20230527T194431
[2023-05-27T19:44:31.983+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 242 for task permissoes_diretorios (expected str, bytes or os.PathLike object, not NoneType; 1898)
[2023-05-27T19:44:32.009+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-27T19:44:32.035+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
