[2023-05-27T19:55:57.884+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:44:17.558652+00:00 [queued]>
[2023-05-27T19:55:57.899+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:44:17.558652+00:00 [queued]>
[2023-05-27T19:55:57.900+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:55:57.900+0000] {taskinstance.py:1280} INFO - Starting attempt 7 of 8
[2023-05-27T19:55:57.900+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-27T19:55:57.922+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): permissoes_diretorios> on 2023-05-27 19:44:17.558652+00:00
[2023-05-27T19:55:57.932+0000] {standard_task_runner.py:55} INFO - Started process 2581 to run task
[2023-05-27T19:55:57.935+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cria_diretorios_projeto', 'permissoes_diretorios', 'manual__2023-05-27T19:44:17.558652+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/cria_diretorios_projeto.py', '--cfg-path', '/tmp/tmpb1orx6t1']
[2023-05-27T19:55:57.936+0000] {standard_task_runner.py:83} INFO - Job 250: Subtask permissoes_diretorios
[2023-05-27T19:55:58.008+0000] {task_command.py:388} INFO - Running <TaskInstance: cria_diretorios_projeto.permissoes_diretorios manual__2023-05-27T19:44:17.558652+00:00 [running]> on host 36658c0564dd
[2023-05-27T19:55:58.097+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cria_diretorios_projeto
AIRFLOW_CTX_TASK_ID=permissoes_diretorios
AIRFLOW_CTX_EXECUTION_DATE=2023-05-27T19:44:17.558652+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-27T19:44:17.558652+00:00
[2023-05-27T19:55:58.099+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-27T19:55:58.099+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "\n            export PATH_FOLDER='/dags'\n            cd $PATH_FOLDER/\n            chmod -R 777 *\n        "]
[2023-05-27T19:55:58.118+0000] {subprocess.py:86} INFO - Output:
[2023-05-27T19:55:58.119+0000] {subprocess.py:93} INFO - /bin/bash: line 3: cd: /dags/: No such file or directory
[2023-05-27T19:55:58.124+0000] {subprocess.py:93} INFO - chmod: cannot access '*': No such file or directory
[2023-05-27T19:55:58.125+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-27T19:55:58.144+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-27T19:55:58.151+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=cria_diretorios_projeto, task_id=permissoes_diretorios, execution_date=20230527T194417, start_date=20230527T195557, end_date=20230527T195558
[2023-05-27T19:55:58.177+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 250 for task permissoes_diretorios (Bash command failed. The command returned a non-zero exit code 1.; 2581)
[2023-05-27T19:55:58.229+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-27T19:55:58.250+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
